version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: laravel-app
    volumes:
      - ./laravel-api:/var/www
    working_dir: /var/www
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    networks:
      - laravel

  webserver:
    image: nginx:alpine
    container_name: laravel-webserver
    ports:
      - "80:80"
    volumes:
      - ./laravel-api:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: laravel-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
